# DEPLOX build-runner base image.
#
# Bakes the toolchains we need for the supported frameworks:
#   - Node 20 (React, Next.js, Node)
#   - Python 3.12 (Python)
#   - Go 1.22 (Go)
#   - nginx 1.27 (static / React post-build)
#
# This image is built once and reused across deployments. Per-deployment
# Dockerfiles (generated by RealDockerProvider) start FROM these layers.

FROM node:20-bookworm AS node-base
RUN npm i -g pnpm@9.12.0 && corepack enable
WORKDIR /work

FROM python:3.12-slim AS python-base
RUN pip install --no-cache-dir uv pip-tools
WORKDIR /work

FROM golang:1.22-bookworm AS go-base
WORKDIR /work

FROM node:20-bookworm AS deplox-build-runner
# Aggregates all toolchains so the per-deployment Dockerfile can do
#   FROM deplox/build-runner:latest
#   COPY . .
#   RUN <framework-specific build commands>
#
# Each framework's Dockerfile is generated at deploy time and is the only
# thing that runs inside user containers — this image never executes user
# code directly.
COPY --from=node-base  /usr/local/bin/node  /usr/local/bin/node
COPY --from=node-base  /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=python-base /usr/local/bin/python3 /usr/local/bin/python3
COPY --from=go-base    /usr/local/go /usr/local/go
ENV PATH=/usr/local/go/bin:/usr/local/lib/node_modules/.bin:$PATH

# Install nginx + CA cert tooling (used by the React + static generators).
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        nginx ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
CMD ["echo", "deplox/build-runner ready"]